# yaml-language-server: $schema=../.vscode/config.schema.yaml

manga:
  title: div.post-title h1
  description: div.summary__content
  cover_url:
    selector: div.summary_image img
    value:
      - data-src
      - src

  status: div.post-status div.summary-content
  authors: div.author-content a
  genres: div.genres-content a
  alt_titles: div.summary-heading:has('h5:icontains("alternative")') + div

  chapter:
    base: li.wp-manga-chapter
    title: a
    url: a
    number: span.chapter-number
    date: span i

    fetch_external:
      - id: script:icontains('mangaid')
        regex: var mangaID = '(\d+)';
        url: /ajax-list-chapter?mangaID={id}

search:
  search_url: "{host}/search?q={query}"
  selectors:
    base: "li"
    url: "a"
    title: "a"

date_formats:
  - "%b-%d-%H:%M"
