name: madara

accept:
  selector:
    - '[href*="madara"]'
  hostnames:
    - isekaiscan.top

manga:
  title:
    selector: div.post-title h1
    options:
      fix_capitalization: title
  description: div.summary__content
  cover_url:
    selector: div.summary_image img
    options:
      text_selection:
        type: attributes
        attributes:
          - data-src
          - src

  status: div.post-status div.summary-content
  authors: div.author-content a
  genres: div.genres-content a
  alt_titles: div.summary-heading:has('h5:icontains("alternative")') + div

  chapter:
    base: li.wp-manga-chapter
    title: a
    url:
      selector: a
      options:
        text_selection:
          type: attributes
          attributes:
            - href
            - src
    number: span.chapter-number
    date: span i

    fetch_external:
      - id: script:icontains('mangaid')
        regex: var mangaID = '(?<id>\d+)';
        url: /ajax-list-chapter?mangaID={id}

images:
  image_selector:
    - selector: p#arraydata
      options:
        text_split_regex: ','
    - selector: img
      options:
        text_selection:
          type: attributes
          attributes:
            - data-src
            - src

search:
  search_url: "{host}/search?q={query}"
  selectors:
    base: "li"
    url: "a"
    title: "a"

date_formats:
  - "%b-%d-%H:%M"
